### ISSUE TITLE
Issues with HLS

### ISSUE THREAD

**Issue by trampolinstudio** [openplayerjs/openplayerjs#246] opened 2021-05-28 07:10 UTC
Hello,

something is causing the audio to halt on this example:

https://codepen.io/rafa8626/pen/abbjrBW

The stream usually stops playing audio after 20/40 seconds.

It happens on multiple different streams, the same thing also happens on our setup. The error we get is "Media download failed part-way due to a network error".

All streams tested work with hls.js without this problem, which makes this issue even more strange - from all the different variants we've tested I don't think it is a server issue or a configuration issue.

1. Go to https://codepen.io/rafa8626/pen/abbjrBW
2. Play the sound
3. Wait for 20/40 seconds
4. Sound stops

Happens on latest Chrome and Safari on MacOS Catalina, Desktop.

Do you maybe know what is causing this issue?

**Comment by rafa8626** [comment] 2021-05-28 10:22
@trampolinstudio thanks for reporting this. I’ll check it and let you know

**Comment by rafa8626** [comment] 2021-05-30 21:09
@trampolinstudio I checked the CodePen you posted above; I left both audios playing for like 5 min and played smoothly. There was an issue with the first one related to not showing the poster image when playing, but I fixed that in the pen. I was not able to reproduce the original issue you posted. If you have an example of this happening somewhere else, let me know so I can take a look

**Comment by trampolinstudio** [comment] 2021-05-30 21:15
@rafa8626 thank you for checking. I just checked and it happened again :) I will send you our staging URL with a password via email, hope that is ok.

**Comment by rafa8626** [comment] 2021-05-30 21:16
@trampolinstudio sure that works

**Comment by rafa8626** [comment] 2021-06-05 13:49
Closing this for now since I wasn’t able to reproduce this. If you have more information about this, let me know. Thanks for choosing OpenPlayerJS!

**Closed by rafa8626** 2021-06-05 13:49 UTC
Labels: bug, more info required
