### ISSUE TITLE
Is it possible to use without the Player default UI

### ISSUE THREAD

**Issue by afkcodes** [openplayerjs/openplayerjs#363] opened 2022-08-27 11:13 UTC
**Describe the bug**
I am trying to use the player without the UI that player offers. I created an audio tag and  i am setting a source array to the player
but when i make a load call the player throws an error . I am using next js. 

**Expected behavior**
Able to play without the default UI with player functions like play,pause,progress and other related APIs

**Screenshots**
![Screenshot 2022-08-27 at 4 38 18 PM](https://user-images.githubusercontent.com/17390257/187027656-7777b67d-4c16-4335-b84e-ba7472fd0ca3.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version latest

**Comment by rafa8626** [comment] 2022-08-27 11:19
@afkcodes thanks for reaching out; I’ve never had a case where you wanted to just use the functionality without the UI. I haven’t ever tested the player without the UI elements so I could see why issues may arise. This could be an improvement in the future release, so if you have a CodePen where I can see exactly what you tried to do, I’d consider to check it and plan it for a future release.
Thanks and please give the project a star to show your support.

**Comment by afkcodes** [comment] 2022-08-27 11:27
sure, i will add a codesandbox, the reason i want the player without the UI is because that will allow me to have my own player design however i want and call the player APIs from anywhere in the entire application. I am currently using the combination of soundmanager2 and hls js that allows me to do the same. This library is far more advanced and this allows me to do the same i would be replacing my solution with this. 
Thanks for being so prompt @rafa8626

**Comment by afkcodes** [comment] 2022-08-27 11:37
Here is a minimal reproduction sandbox: https://codesandbox.io/s/dreamy-gwen-r84i8z

Kudos to you @rafa8626 and other contributors for the amazing work on this, i would also love to contribute to on the new website overhaul, i saw that issue please let me know if i can. 
I have starred the repo, how could i miss that. hope this feature comes soon. 
Here is my current solution (soundmanager2 + hls js): https://radio-india.vercel.app

**Comment by rafa8626** [comment] 2022-08-27 12:06
@afkcodes thanks for starting the project; I’ll be checking your sample and once I have the website in a more mature state, I’ll let you know 😁I’ll keep you posted on any progress about this

**Comment by rafa8626** [comment] 2022-08-27 14:22
@afkcodes please download the master branch and test this again; I have a fix for your problem: turns out I did have support for what you needed but I wasn't supporting your specific user case with no source at all when starting. Please check it and let me know so I can release it as a fix

**Comment by afkcodes** [comment] 2022-08-27 17:17
@rafa8626 sure will check this and report, thanks you are amazing.

**Comment by afkcodes** [comment] 2022-08-27 17:35
@rafa8626 Yes the fix works but i have to test it more, at the initial impression what i see is wherever i am declaring the audio tag that whole element is getting removed from the dom tree, don't know whats the issue, will create a minimal reprodcution for this. I see load and play methods working fine but destroy still throws the error.

Also is there anyway to get methods for the state of the player like - buffering, playing, stopped, error, progress, duration and other related info such as meta data.

**Comment by rafa8626** [comment] 2022-08-27 17:49
@afkcodes I'll check what's the issue with destroy() when you post the CodePen because I tried to replicate it without success; in order to get access to the events you want, you can do 
```javascript
zPlayer.getElement().addEventListener('canplay', ...);
```
In terms of the DOM getting removed, I'm not sure why, since nothing in my code removes DOM, only if it's a video under a specific mode to present it, but other than that, it shouldn't remove anything

**Comment by afkcodes** [comment] 2022-08-27 18:04
yes i looked into the docs and now playing with the events that openplayerjs has to offer the dom was getting removed because i was passing the wrong source type to the src. that is fine now. i was trying to create a repro but was not able to on codesandbox will create a repo and share it with you. 

one more query is there a way to stop player and clear the source and add new one. currently when i do the same it adds a new source element inside the audio element. 
![Screenshot 2022-08-27 at 11 33 17 PM](https://user-images.githubusercontent.com/17390257/187042536-d4b8e7dc-1e22-4af8-851a-19875d17abe3.png)

this is the reason i was looking for destroy, but i think calling destroy and reinitializing the player is not a good way to handle the situation.

**Comment by rafa8626** [comment] 2022-08-27 18:50
@afkcodes by just setting the source should do it without adding extra elements. Something like this should work: 
```javascript
zPlayer.src = "https://ccrma.stanford.edu/~jos/mp3/Latin.mp3";
zPlayer.load();
```
You don't always need to set the type; the player is smart enough to detect it, but sometimes you can force the MIME type. Let me know if that worked

**Comment by afkcodes** [comment] 2022-08-27 20:37
got it i will try this

**Comment by rafa8626** [comment] 2022-08-28 11:29
@afkcodes thats great that you were able to integrate the player! In terms of the getMedia() issue, that’s because you haven’t set a media source yet, so you are truly starting without media and that’s expected.

I will check the destroy method today; and if the only method you are trying to expose is stop I can add it.

In terms of the audio, it is weird because the player is not muting anything unless you are attempting an autoplay. If that’s the case, maybe that’s why is muting it.

**Comment by afkcodes** [comment] 2022-08-28 14:44
@rafa8626  I am not muting the audio not i am doing an autoplay the  url you can see the behaviour and check it on mobile as well on your side. 
here is the latest Preview URL with OpenPlayerJS: https://radio-india-git-feature-openplayer-js-afkcodes.vercel.app/


and about the getMedia() should it give me the media details once i play some audio ? or else i will not be able to set sound and other media events.  

if you can debug at your side a bit about the audio volume on the mobile.

**Comment by rafa8626** [comment] 2022-08-28 14:58
It should but to be safe if you can to reproduce everything you are trying to achieve in a CodePen will help me a lot, since at least I can manipulate things easier there

**Comment by rafa8626** [comment] 2022-08-28 15:01
BTW, I can hear the audio just fine when I attempt to play it. I’m using iOS if that matters

**Comment by afkcodes** [comment] 2022-08-28 15:04
here is the github repo for the openplayer js integration: https://github.com/afkcodes/radio_india/tree/feature/openplayer-js

you can run this on local and see the issue being seen

**Comment by afkcodes** [comment] 2022-08-28 15:06
> BTW, I can hear the audio just fine when I attempt to play it. I’m using iOS if that matters

tested on iOS too, seems working fine the issue seems to happen only on Android

**Comment by rafa8626** [comment] 2022-08-28 15:09
Interesting; I’ll need an emulator to check that since I don’t have Android devices with me; do you have a SauceLab or Browserstack account to troubleshoot this? Also, I see some issues with the way you did things. I’ll put some comments on your project based so you can correct them

**Comment by afkcodes** [comment] 2022-08-28 15:20
@rafa8626 sorry i dont have an browserstack account. 
and thanks for the comments i will check them and update accordingly.

**Comment by afkcodes** [comment] 2022-08-28 18:31
The observation that i have is it only happens with hls audios in android device. @rafa8626 
This: https://radio-india.vercel.app 
is using hls js but it doesnt have that issue all works fine and the same logic i have tried to implement with openPlayerJS

**Comment by rafa8626** [comment] 2022-08-28 18:34
@afkcodes gotcha; maybe it has to do with the fact that Android tries to use native rather than hls; I’ll check it but that’s my best guess based on what you described. I have comments on your branch, and I’ll post them later today. That would make the code cleaner and potentially solve your Android issue

**Comment by afkcodes** [comment] 2022-08-28 18:43
i am hopeful, thanks @rafa8626  
Here is the older implementation of the hls player if you want to have a look at it: https://github.com/afkcodes/radio_india/blob/main/src/modules/player.ts

**Comment by rafa8626** [comment] 2022-08-28 19:05
Yeah, this is using hls.js completely; I’ll give you the setup to mimic this on my comments

**Comment by afkcodes** [comment] 2022-08-28 19:08
sure thank again, this will be a great help.

**Comment by afkcodes** [comment] 2022-08-28 19:20
seems like this might be the issue, the hlsMediaAttached event is not being fired on android whereas in web its being called on the web.

**Comment by rafa8626** [comment] 2022-08-28 19:29
Seems I can't post comments there; I can send you the modified file, but I'll need an email to send it to you. Let me know if that works for you

**Comment by rafa8626** [comment] 2022-08-28 19:42
nvm I was able to post comments now :)

**Comment by afkcodes** [comment] 2022-08-28 19:48
> nvm I was able to post comments now :) let me know if you have questions. I have created a stop method, so make sure your project pulls the latest commit from master

have taken a latest pull from master

**Comment by afkcodes** [comment] 2022-08-28 19:53
Finally the issue got fixed, thanks @rafa8626 can you explain me what did i do wrong.

**Comment by rafa8626** [comment] 2022-08-28 19:56
@afkcodes as I stated before, the player favors native playing; because of that, and because Android can play natively HLS, the player will try to play it as a regular source without HLS. So, in order to force HLS to play it, the `forceNative` should be set as false in the player configuration

**Comment by rafa8626** [comment] 2022-08-28 20:01
Closing this issue now; once you have your project live, could you provide me a URL and logo to showcase it with the other projects that use OpenPlayerJS, please?

I'll release the next version next week, so you can use a proper version in your project. Thanks for your help as well :)

**Closed by rafa8626** 2022-08-28 20:01 UTC
Labels: bug, awaiting confirmation

**Comment by afkcodes** [comment] 2022-08-28 20:10
Yeah will be more than happy to contribute in anyway i can the current project is just a prototype, i was trying multiple solutions that were not suiting my case and fortunately i found openPlayerJS this library is just superb. This needs more attention just keep the good work going and this will be the best audio utility. 

will surely help you with logo and other stuff once i the project goes live.

**Comment by rafa8626** [comment] 2022-08-28 20:14
Yeah, the best way to help with this library is to continue testing it in different scenarios. I'm working on cleaning up code more and make it more robust and flexible, and that's where you could help me once I reach a good point to test it. I will still be working on getting better unit tests but it's always good to have a second pair of eyes on this.

If you have other friends that are on GitHub, please ask them to star the project so it gains more notoriety, or if you have any ideas how to make it more popular, I'm all open to new ideas :)

**Comment by afkcodes** [comment] 2022-08-28 20:22
yes, sure i will surely help because what i am trying to make is going to i will come across more scenarios and will share it with you so that we can make this library a full fledged utility. 

I will surely ask my friends to star the repo. And from the popularity prospect i am going to make a youtube tutorial for making a online radio website using openPlayerJS. and surely will think more ways for the same.

**Comment by rafa8626** [comment] 2022-08-28 20:27
I truly appreciate your help on this :) Let me know if something else comes up

**Comment by afkcodes** [comment] 2022-08-28 20:36
sure thank you again :)

**Comment by afkcodes** [comment] 2022-08-28 20:39
![Screenshot 2022-08-29 at 2 07 53 AM](https://user-images.githubusercontent.com/17390257/187093577-b86aff1b-2189-42d2-a340-598b94988bc8.png)

@rafa8626 Sometimes i get this error, do you know why this happens only the error appears but playback doesn't seems to be affected in anyway.

**Comment by rafa8626** [comment] 2022-08-28 20:41
That seems to be an streaming error processed by HLS; I'd enclose this call within a setTimeout and give it like 200 ms before loading it and see if that helps

**Comment by afkcodes** [comment] 2022-08-28 20:42
![Screenshot 2022-08-29 at 2 11 35 AM](https://user-images.githubusercontent.com/17390257/187093705-0f77a9d5-3292-44a2-9511-dc2df7f3910e.png)

and this is more frequent but, playback is fine

**Comment by afkcodes** [comment] 2022-08-28 20:44
> That seems to be an streaming error processed by HLS; I'd enclose this call within a setTimeout and give it like 200 ms before loading it and see if that helps

this is not an hls audio this is an mp3 or aac i guess

**Comment by rafa8626** [comment] 2022-08-28 20:44
I'll check this, because it's pointing to the HTML5 media type for some reason

**Comment by rafa8626** [comment] 2022-08-28 20:45
can you tell me which source is the one throwing this error?

**Comment by afkcodes** [comment] 2022-08-28 20:45
> can you tell me which source is the one throwing this error?

Here is the Source: https://funasia.streamguys1.com/live4

**Comment by afkcodes** [comment] 2022-08-28 20:47
![Screenshot 2022-08-29 at 2 16 57 AM](https://user-images.githubusercontent.com/17390257/187093885-4580e045-60f4-45e1-bc10-58f97a1f17b7.png)

This is this one in my app

**Comment by rafa8626** [comment] 2022-08-28 21:31
I can't replicate the error on my end; all plays as expected. The error seems to have something to do with the streaming itself

**Comment by afkcodes** [comment] 2022-08-29 12:37
thanks for confirming this.
