### ISSUE TITLE
Dual boot hls links

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#26] opened 2018-11-06 17:49 UTC
Hey rafa! After the latest updates, I had a double boot hls player.
1 before advertising, 2 after advertising. Sometimes 5-6 (look image)

It spoils all my add-ons for example p2p-hls.

I also noticed problems with the VAST list when one or both of the lists do not issue ads.

![Imgur](https://i.imgur.com/96WGnMJ.png)

https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcdn11.anivid.nut.cc%2Fvid%2Fs1%2F85%2F1.mp4%2Fplaylist.m3u8&type=video&ads=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D640x480%26iu%3D%2F124319096%2Fexternal%2Fad_rule_samples%26ciu_szs%3D300x250%26ad_rule%3D1%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dvmap%26unviewed_position_start%3D1%26cust_params%3Ddeployment~3Ddevsite~26sample_ar~3Dpremidpostoptimizedpod%26cmsid%3D496%26vid%3Dshort_onecue%26correlator%3D

ps you did not think to write a plugin for VAST?
Vdeojs recently released an SDK.

**Comment by rafa8626** [comment] 2018-11-07 03:02
@supersh86 Oddly enough, I couldn't reproduce your issue. See screenshot.
<img width="602" alt="screen shot 2018-11-06 at 10 01 12 pm" src="https://user-images.githubusercontent.com/910829/48108026-93fcb880-e20f-11e8-91ca-9ea0c3b1554e.png">

As far as writing for VAST, Google IMA supports VAST, VPAID and VMAP formats, so that's covered.

**Comment by supersh86** [comment] 2018-11-07 08:31
Clear cashe and use filter in network panel.
I'am testing in Chrome & Firefox

[!Imgur](https://i.imgur.com/vnfTb7K.png)

**Comment by rafa8626** [comment] 2018-11-09 03:40
I'll try to check what can cause this in more depth; which version was the last one you used to test this and you didn't get the double request?

**Comment by supersh86** [comment] 2018-11-09 07:11
I find it difficult to answer

I just looked at the statistics of server traffic for the month and saw a huge increase, and then I learned that p2p stopped working in October.

**Comment by supersh86** [comment] 2018-11-09 13:15
In my original code, I use source and type.
But the problem is not solved.
    
<video id="hlsvideo" class="op-player__media" controls playsinline>
       <source src="../playlist.m3u8" type="application/x-mpegURL">
    </video>

**Comment by rafa8626** [comment] 2018-11-12 03:57
Please download the master branch and test this issue again; I figured out why it was doing the double request. As far as the library you showed me, it may be good for your purposes but it's limited since it's only for VAST, and as far as I can see, only for pre-roll Ads, so I'm interested on supporting libraries that benefit most people in the long term

**Comment by supersh86** [comment] 2018-11-12 04:36
on my server, and on the example in the first message. The problem is not fixed.

**Comment by rafa8626** [comment] 2018-11-12 04:39
On the embed I haven't released a new version with the fix, since it uses CDN for it. Once you confirm on your side that no duplicates are coming up using the master branch, I'll release the new version and the embed will carry that fix. To test this use a CodePen and the https://raw.githubusercontent.com/openplayerjs/openplayerjs/master/dist/openplayer.js URL

**Comment by supersh86** [comment] 2018-11-12 15:04
Yes! Its fix!

**Comment by rafa8626** [comment] 2018-11-12 15:15
Perfect I’ll release today in a bit :)

**Comment by supersh86** [comment] 2018-11-12 17:54
And if it's not hard to look at it. I have problems with the vast list. It is also not clear when she appeared.
https://codepen.io/anon/pen/rQWdNK

**Comment by rafa8626** [comment] 2018-11-13 05:55
@supersh86 Please test once more using master branch. I fixed your issue with the VAST list. Let me know so I can release the next version. Thanks

**Comment by supersh86** [comment] 2018-11-13 07:53
The image of the play button disappears late.
If the event is a load, then it would be good to indicate the desired animation.

**Comment by rafa8626** [comment] 2018-11-13 12:11
I have added the loading animation before the Ad plays; let me know if that works for you

**Comment by supersh86** [comment] 2018-11-13 18:08
Yes, the download animation.

Unfortunately, she worked for a few seconds.

If Chunks load for 5-7 seconds, the animation runs for 1-3 seconds.

**Comment by rafa8626** [comment] 2018-11-13 23:29
@supersh86 it's hard to debug that. Can you provide a CodePen with that issue please?

**Comment by supersh86** [comment] 2018-11-14 01:19
https://codepen.io/anon/pen/gQmYNN
This problem can be caught only in the evening when the servers are loaded.
At 9 o'clock UTC + 3

**Comment by rafa8626** [comment] 2018-11-14 05:08
Gotcha. I think I have fixed the issue you presented in the CodePen. Try the master branch again and let me know if it worked for you

**Comment by rafa8626** [comment] 2018-11-14 12:52
@supersh86 I just did one last fix and I think this is all set. Once you confirm about this one, I'll release. Thanks

**Comment by supersh86** [comment] 2018-11-14 18:36
The animation does not disappear when the video starts.)))

**Comment by rafa8626** [comment] 2018-11-14 18:37
in that same CodePen you shared?

**Comment by rafa8626** [comment] 2018-11-26 11:31
@supersh86 hey, I assume the issue has to do with the Ads not being played? I see 2 of them and IMA returned an error for the first one but the second one doesn't play
<img width="439" alt="screen shot 2018-11-26 at 6 27 30 am" src="https://user-images.githubusercontent.com/910829/49011623-e5300600-f144-11e8-98b7-101b350977d0.png">

**Comment by supersh86** [comment] 2018-11-26 12:13
No, the problem is that the player works with an error.
No animation button press play, after starting the video pause does not disappear.

I will write you a video

**Comment by rafa8626** [comment] 2018-11-26 12:33
The icon doesn’t disappear since you are moving the mouse constantly. It’s one of the behaviors I implemented but had an issue before

**Comment by supersh86** [comment] 2018-11-26 13:08
look 0:05 time.
Icon its freeze

**Comment by rafa8626** [comment] 2018-11-26 13:14
I see. Let me check why and I’ll get back to you

**Comment by rafa8626** [comment] 2018-11-27 11:38
https://streamable.com/orqsg
As you can see, if you don't move the mouse, the icon disappear. If the video is paused, the icon will be visible. If the control bar is visible you will see the icon, but if the control bar disappears, the icon disappears too. I did notice that clicking in the big pause button didn't pause the video so I'm looking into that right now

**Comment by rafa8626** [comment] 2018-11-27 11:53
@supersh86 Ok I have fixed the big play button behavior. Please test the master branch and let me know so I can release the fixes today. Thanks

**Comment by supersh86** [comment] 2018-11-27 12:40
Now the video refuses to run.
https://codepen.io/anon/pen/jQvExG

**Comment by rafa8626** [comment] 2018-11-27 13:01
It plays on my side. Sometimes I see delays but that has nothing to do with the player itself

**Comment by supersh86** [comment] 2018-11-27 13:05
Strangely, my player hangs up and can not start the video.

**Comment by supersh86** [comment] 2018-11-27 15:50
In Chrome
https://streamable.com/5sm9e

**Comment by rafa8626** [comment] 2018-11-28 02:50
I used Chrome and this was my result (even clearing all the cache)
https://streamable.com/f7cgn

**Comment by supersh86** [comment] 2018-11-28 06:21
)))) disable ads filter)) s'il vous plait)))

**Comment by supersh86** [comment] 2018-11-28 08:36
I see a strange error in the console. The forums write about this as an error on mobile devices.
```
ima3.js:348 Uncaught 
zp {l: "Failed to initialize ad playback element before starting ad playback.", h: 400, o: "adPlayError", g: null}
g: null
h: 400
l: "Failed to initialize ad playback element before starting ad playback."
o: "adPlayError"
__proto__: Error
```

**Comment by rafa8626** [comment] 2018-11-28 11:58
@supersh86 Finally I was able to reproduce your bug. I saw the error as well as I fixed that. Please test master branch once more and let me know if it's fixed please. Thanks and sorry for the incovenience

**Comment by supersh86** [comment] 2018-11-28 12:10
YES!
It would be ideal if during loading and initialization of the vast xml list, the loading icon would be displayed.

**Comment by rafa8626** [comment] 2018-11-28 12:12
Let me see if I can add that. I’m glad this was solved too!

**Comment by rafa8626** [comment] 2018-11-28 13:00
Closing this issue now. I'll let you know if I was able to integrate the loading element during initialization.

**Closed by rafa8626** 2018-11-28 13:00 UTC
Labels: awaiting confirmation

**Comment by supersh86** [comment] 2018-11-28 13:01
Ok! thx!

**Comment by rafa8626** [comment] 2018-11-28 15:31
@supersh86 I updated the code so you should see now the loader while waiting to play Ads/media/ Please test the master branch and let me know if it worked for you. Thanks

**Comment by supersh86** [comment] 2018-11-28 19:07
Unfortunately, the VPAID loading is not displayed correctly and the loading of the first chunk appeared, which is not always correct.
Usually inside the VPAID there may be its own independent player, the loader does not display it correctly.
https://streamable.com/qbwg2
I usually use youtube advertising for other tasks, but your player can be used for a silent video banner. So this plot is also worth considering.

**Comment by rafa8626** [comment] 2018-11-28 19:59
so you are saying that the loader should disappear once the VPAID player is ready correct?

**Comment by rafa8626** [comment] 2018-11-29 03:52
Please share a CodePen where I can see the issue, so I can take a look and fix it

**Comment by rafa8626** [comment] 2018-12-03 12:05
@supersh86 Can you test the master branch once more, please? I removed an event that introduced the loader and I think it was unnecessary. Let me know if that worked for you

**Comment by supersh86** [comment] 2018-12-14 06:04
Hi, everything seems to be working well, now I'll write a new idea.
