### ISSUE TITLE
iframe attributes

### ISSUE THREAD

**Issue by komato3huk** [openplayerjs/openplayerjs#178] opened 2020-11-07 06:46 UTC
iframe.setAttribute('allow', 'fullscreen'); // must be 1st
iframe.setAttribute('allowFullScreen', '');
please add this in repo

**Comment by komato3huk** [comment] 2020-11-07 09:29
this neen to normal working ads

**Comment by rafa8626** [comment] 2020-11-07 13:04
@komato3huk this change is for the OpenPlayerJS website correct?

**Comment by rafa8626** [comment] 2020-11-07 13:19
@komato3huk where is this needed exactly? I can’t find the reference in the code

**Comment by komato3huk** [comment] 2020-11-08 07:33
Hi. 
This need to initialization iframe ads.

**Comment by rafa8626** [comment] 2020-11-08 13:18
The iframe is created by the IMA SDK library not by OpenPlayerJS per se. If anything this is something it should be requested to that team.

**Comment by rafa8626** [comment] 2020-11-08 13:21
If I read the docs correctly you don’t need that since they have a command to resize the ads or play it full screen correctly and that was integrated in OpenPlayerJS. Is there an issue by not adding those values in the iframe?

**Comment by rafa8626** [comment] 2020-11-08 13:34
This what the docs say:

> The IMA SDK supports a simulated full screen mode, in which the video takes up the whole browser window. We consider a video to be in full screen mode when its offsetWidth and offsetHeight are at least the size of the document body. This mode is supported on all browsers... On the iPhone and pre-3.0 Android platforms, video will always play back in full screen mode.

That’s why they don’t include that attribute as far as I can see

**Comment by komato3huk** [comment] 2020-11-08 14:21
![image](https://user-images.githubusercontent.com/22004977/98467516-cf5b6480-21e6-11eb-9b8b-b8fa8948455e.png)

**Comment by rafa8626** [comment] 2020-11-08 15:41
Let me see what I can do to remove the warning

**Comment by rafa8626** [comment] 2020-11-08 16:45
@komato3huk I tested this with the latest version of the player, and if I add those lines, the warning comes up, but if I don't do anything, the warning disappears. Is there anything special on your setup I may not be aware of? Also, my version of Chrome is 86.0.4240.183

**Comment by rafa8626** [comment] 2020-11-25 16:19
@komato3huk closing this issue since there are no more details about it and I haven't been able to reproduce it. If you still experience issues,  please provide a CodePen where I can check the issue and I'll reopen this issue

**Closed by rafa8626** 2020-11-25 16:19 UTC
Labels: more info required
